# generated by datamodel-codegen:
#   filename:  2026-04-24.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from openresponses.types.base import OpenResponsesModel
from pydantic import ConfigDict, Field, RootModel
from typing_extensions import TypeAliasType


class ItemReferenceParam(OpenResponsesModel):
    """
    An internal identifier for an item to reference.
    """

    type: Literal['item_reference'] | None = None
    id: str
    """
    The ID of the item to reference.
    """


class ReasoningSummaryContentParam(OpenResponsesModel):
    type: Literal['summary_text']
    """
    The content type. Always `summary_text`.
    """
    text: Annotated[str, Field(max_length=10485760)]
    """
    The reasoning summary text.
    """


class ReasoningItemParam(OpenResponsesModel):
    id: str | None = None
    type: Literal['reasoning']
    """
    The item type. Always `reasoning`.
    """
    summary: list[ReasoningSummaryContentParam]
    """
    Reasoning summary content associated with this item.
    """
    content: None = None
    encrypted_content: str | None = None


class CompactionSummaryItemParam(OpenResponsesModel):
    """
    A compaction item generated by the [`v1/responses/compact` API](/docs/api-reference/responses/compact).
    """

    id: str | None = None
    type: Literal['compaction']
    """
    The type of the item. Always `compaction`.
    """
    encrypted_content: Annotated[str, Field(max_length=10485760)]
    """
    The encrypted content of the compaction summary.
    """


class InputTextContentParam(OpenResponsesModel):
    """
    A text input to the model.
    """

    type: Literal['input_text']
    """
    The type of the input item. Always `input_text`.
    """
    text: Annotated[str, Field(max_length=10485760)]
    """
    The text input to the model.
    """


class DetailEnum(RootModel[Literal['low', 'high', 'auto']]):
    root: Literal['low', 'high', 'auto']


class ImageUrl(RootModel[str]):
    root: Annotated[str, Field(max_length=20971520)]
    """
    The URL of the image to be sent to the model. A fully qualified URL or base64 encoded image in a data URL.
    """


class FileData(RootModel[str]):
    root: Annotated[str, Field(max_length=33554432)]
    """
    The base64-encoded data of the file to be sent to the model.
    """


class InputFileContentParam(OpenResponsesModel):
    """
    A file input to the model.
    """

    type: Literal['input_file']
    """
    The type of the input item. Always `input_file`.
    """
    filename: str | None = None
    file_data: FileData | None = None
    file_url: str | None = None


class Content1(RootModel[str]):
    root: Annotated[str, Field(max_length=10485760)]
    """
    The message content, as a single string.
    """


class Content2(RootModel[InputTextContentParam]):
    root: Annotated[InputTextContentParam, Field(discriminator='type')]


class Content3(RootModel[str]):
    root: Annotated[str, Field(max_length=10485760)]
    """
    The message content, as a single string.
    """


class SystemMessageItemParam(OpenResponsesModel):
    id: str | None = None
    type: Literal['message']
    """
    The item type. Always `message`.
    """
    role: Literal['system']
    """
    The message role. Always `system`.
    """
    content: list[Content2] | Content3
    """
    The message content, as an array of content parts.
    """
    status: str | None = None


class Content4(RootModel[InputTextContentParam]):
    root: Annotated[InputTextContentParam, Field(discriminator='type')]


class Content5(RootModel[str]):
    root: Annotated[str, Field(max_length=10485760)]
    """
    The message content, as a single string.
    """


class DeveloperMessageItemParam(OpenResponsesModel):
    id: str | None = None
    type: Literal['message']
    """
    The item type. Always `message`.
    """
    role: Literal['developer']
    """
    The message role. Always `developer`.
    """
    content: list[Content4] | Content5
    """
    The message content, as an array of content parts.
    """
    status: str | None = None


class UrlCitationParam(OpenResponsesModel):
    type: Literal['url_citation']
    """
    The citation type. Always `url_citation`.
    """
    start_index: Annotated[int, Field(ge=0)]
    """
    The index of the first character of the citation in the message.
    """
    end_index: Annotated[int, Field(ge=0)]
    """
    The index of the last character of the citation in the message.
    """
    url: str
    """
    The URL of the cited resource.
    """
    title: str
    """
    The title of the cited resource.
    """


class OutputTextContentParam(OpenResponsesModel):
    type: Literal['output_text']
    """
    The content type. Always `output_text`.
    """
    text: Annotated[str, Field(max_length=10485760)]
    """
    The text content.
    """
    annotations: list[UrlCitationParam] | None = None
    """
    Citations associated with the text content.
    """


class RefusalContentParam(OpenResponsesModel):
    type: Literal['refusal']
    """
    The content type. Always `refusal`.
    """
    refusal: Annotated[str, Field(max_length=10485760)]
    """
    The refusal text.
    """


class Content6(RootModel[OutputTextContentParam | RefusalContentParam]):
    root: Annotated[
        OutputTextContentParam | RefusalContentParam, Field(discriminator='type')
    ]
    """
    A piece of assistant message content, such as text or a refusal.
    """


class Content7(RootModel[str]):
    root: Annotated[str, Field(max_length=10485760)]
    """
    The message content, as a single string.
    """


class AssistantMessageItemParam(OpenResponsesModel):
    id: str | None = None
    type: Literal['message']
    """
    The item type. Always `message`.
    """
    role: Literal['assistant']
    """
    The role of the message author. Always `assistant`.
    """
    content: list[Content6] | Content7
    """
    The message content, as an array of content parts.
    """
    phase: Literal['commentary', 'final_answer'] | None = None
    """
    Labels an `assistant` message as intermediate commentary (`commentary`) or the final answer (`final_answer`). For models like `gpt-5.3-codex` and beyond, when sending follow-up requests, preserve and resend phase on all assistant messages. Omitting it can degrade performance. Not used for user messages.
    """
    status: str | None = None


class FunctionCallItemStatus(
    RootModel[Literal['in_progress', 'completed', 'incomplete']]
):
    root: Literal['in_progress', 'completed', 'incomplete']


class Output(RootModel[str]):
    root: Annotated[str, Field(max_length=10485760)]
    """
    A JSON string of the output of the function tool call.
    """


class IncludeEnum(
    RootModel[Literal['reasoning.encrypted_content', 'message.output_text.logprobs']]
):
    root: Literal['reasoning.encrypted_content', 'message.output_text.logprobs']


class EmptyModelParam(OpenResponsesModel):
    pass


class FunctionToolParam(OpenResponsesModel):
    name: Annotated[str, Field(max_length=64, min_length=1, pattern='^[a-zA-Z0-9_-]+$')]
    description: str | None = None
    parameters: EmptyModelParam | None = None
    strict: bool | None = None
    type: Literal['function']


class ResponsesToolParam(RootModel[FunctionToolParam]):
    root: Annotated[FunctionToolParam, Field(discriminator='type')]


class SpecificFunctionParam(OpenResponsesModel):
    type: Literal['function']
    """
    The tool to call. Always `function`.
    """
    name: str
    """
    The name of the function tool to call.
    """


class SpecificToolChoiceParam(RootModel[SpecificFunctionParam]):
    root: SpecificFunctionParam


class ToolChoiceValueEnum(RootModel[Literal['none', 'auto', 'required']]):
    root: Literal['none', 'auto', 'required']


class AllowedToolsParam(OpenResponsesModel):
    type: Literal['allowed_tools']
    """
    The tool choice type. Always `allowed_tools`.
    """
    tools: Annotated[list[SpecificToolChoiceParam], Field(max_length=128, min_length=1)]
    """
    The list of tools that are permitted for this request.
    """
    mode: ToolChoiceValueEnum | None = None


class ToolChoiceParam(
    RootModel[SpecificToolChoiceParam | ToolChoiceValueEnum | AllowedToolsParam]
):
    root: SpecificToolChoiceParam | ToolChoiceValueEnum | AllowedToolsParam
    """
    Controls which tool the model should use, if any.
    """


MetadataParamAdditionalProperty = TypeAliasType(
    "MetadataParamAdditionalProperty", Annotated[str, Field(max_length=512)]
)


class MetadataParam(RootModel[dict[str, MetadataParamAdditionalProperty]]):
    """
    Set of 16 key-value pairs that can be attached to an object. This can be         useful for storing additional information about the object in a structured         format, and querying for objects via API or the dashboard.
            Keys are strings with a maximum length of 64 characters. Values are strings         with a maximum length of 512 characters.
    """

    root: Annotated[dict[str, MetadataParamAdditionalProperty], Field(max_length=16)]


class VerbosityEnum(RootModel[Literal['low', 'medium', 'high']]):
    root: Literal['low', 'medium', 'high']


class StreamOptionsParam(OpenResponsesModel):
    """
    Options that control streamed response behavior.
    """

    include_obfuscation: bool | None = None
    """
    Whether to obfuscate sensitive information in streamed output. Defaults to `true`.
    """


class ReasoningEffortEnum(RootModel[Literal['none', 'low', 'medium', 'high', 'xhigh']]):
    root: Literal['none', 'low', 'medium', 'high', 'xhigh']


class ReasoningSummaryEnum(RootModel[Literal['concise', 'detailed', 'auto']]):
    root: Literal['concise', 'detailed', 'auto']


class ReasoningParam(OpenResponsesModel):
    """
    **gpt-5 and o-series models only** Configuration options for [reasoning models](https://platform.openai.com/docs/guides/reasoning).
    """

    effort: ReasoningEffortEnum | None = None
    summary: ReasoningSummaryEnum | None = None


class TruncationEnum(RootModel[Literal['auto', 'disabled']]):
    root: Literal['auto', 'disabled']


class ServiceTierEnum(RootModel[Literal['auto', 'default', 'flex', 'priority']]):
    root: Literal['auto', 'default', 'flex', 'priority']


class Input(RootModel[str]):
    root: Annotated[str, Field(max_length=10485760)]
    """
    Context to provide to the model for the scope of this request. May either be a string or an array of input items. If a string is provided, it is interpreted as a user message.
    """


class ToolChoice1(OpenResponsesModel):
    pass


class ToolChoice2(ToolChoice1):
    pass


class ToolChoice4(AllowedToolsParam, ToolChoice1):
    pass


class ToolChoice(RootModel[ToolChoice2 | ToolChoice4]):
    root: ToolChoice2 | ToolChoice4


class MaxOutputTokens(RootModel[int]):
    root: Annotated[int, Field(ge=16)]
    """
    The maximum number of tokens the model may generate for this response.
    """


class MaxToolCalls(RootModel[int]):
    root: Annotated[int, Field(ge=1)]
    """
    The maximum number of tool calls the model may make while generating the response.
    """


class SafetyIdentifier(RootModel[str]):
    root: Annotated[str, Field(max_length=64)]
    """
    A stable identifier used for safety monitoring and abuse detection.
    """


class PromptCacheKey(RootModel[str]):
    root: Annotated[str, Field(max_length=64)]
    """
    A key to use when reading from or writing to the prompt cache.
    """


class TopLogprobs(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=20)]
    """
    The number of most likely tokens to return at each position, along with their log probabilities.
    """


class StreamOptions(RootModel[StreamOptionsParam]):
    root: Annotated[StreamOptionsParam, Field(max_length=0, min_length=1)]
    """
    This HTTP streaming options field MUST NOT be sent in WebSocket `response.create` messages.
    """


class StreamOptions1(RootModel[None]):
    root: Annotated[None, Field(max_length=0, min_length=1)]
    """
    This HTTP streaming options field MUST NOT be sent in WebSocket `response.create` messages.
    """


class Error(OpenResponsesModel):
    """
    The WebSocket error payload.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    type: str | None = None
    """
    The error type, when supplied.
    """
    code: str
    """
    A machine-readable error code.
    """
    message: str
    """
    A human-readable error message.
    """
    param: str | None = None


class WebSocketErrorEvent(OpenResponsesModel):
    """
    A WebSocket error envelope returned for Responses WebSocket mode failures.
    """

    type: Literal['error']
    """
    The event type. Always `error`.
    """
    status: int
    """
    The HTTP-style status code for the WebSocket error.
    """
    error: Error
    """
    The WebSocket error payload.
    """


class IncompleteDetails(OpenResponsesModel):
    """
    Details about why the response was incomplete.
    """

    reason: str
    """
    The reason the response could not be completed.
    """


class MessageRole(RootModel[Literal['user', 'assistant', 'system', 'developer']]):
    root: Literal['user', 'assistant', 'system', 'developer']


class InputTextContent(OpenResponsesModel):
    """
    A text input to the model.
    """

    type: Literal['input_text']
    """
    The type of the input item. Always `input_text`.
    """
    text: str
    """
    The text input to the model.
    """


class UrlCitationBody(OpenResponsesModel):
    """
    A citation for a web resource used to generate a model response.
    """

    type: Literal['url_citation']
    """
    The type of the URL citation. Always `url_citation`.
    """
    url: str
    """
    The URL of the web resource.
    """
    start_index: int
    """
    The index of the first character of the URL citation in the message.
    """
    end_index: int
    """
    The index of the last character of the URL citation in the message.
    """
    title: str
    """
    The title of the web resource.
    """


class Annotation(RootModel[UrlCitationBody]):
    root: Annotated[UrlCitationBody, Field(discriminator='type')]
    """
    An annotation that applies to a span of output text.
    """


class TopLogProb(OpenResponsesModel):
    """
    The top log probability of a token.
    """

    token: str
    logprob: float
    bytes: list[int]


class LogProb(OpenResponsesModel):
    """
    The log probability of a token.
    """

    token: str
    logprob: float
    bytes: list[int]
    top_logprobs: list[TopLogProb]


class OutputTextContent(OpenResponsesModel):
    """
    A text output from the model.
    """

    type: Literal['output_text']
    """
    The type of the output text. Always `output_text`.
    """
    text: str
    """
    The text output from the model.
    """
    annotations: list[Annotation]
    """
    The annotations of the text output.
    """
    logprobs: list[LogProb] | None = None


class TextContent(OpenResponsesModel):
    """
    A text content.
    """

    type: Literal['text']
    text: str


class SummaryTextContent(OpenResponsesModel):
    """
    A summary text from the model.
    """

    type: Literal['summary_text']
    """
    The type of the object. Always `summary_text`.
    """
    text: str
    """
    A summary of the reasoning output from the model so far.
    """


class ReasoningTextContent(OpenResponsesModel):
    """
    Reasoning text from the model.
    """

    type: Literal['reasoning_text']
    """
    The type of the reasoning text. Always `reasoning_text`.
    """
    text: str
    """
    The reasoning text from the model.
    """


class RefusalContent(OpenResponsesModel):
    """
    A refusal from the model.
    """

    type: Literal['refusal']
    """
    The type of the refusal. Always `refusal`.
    """
    refusal: str
    """
    The refusal explanation from the model.
    """


class ImageDetail(RootModel[Literal['low', 'high', 'auto']]):
    root: Literal['low', 'high', 'auto']


class InputImageContent(OpenResponsesModel):
    """
    An image input to the model. Learn about [image inputs](/docs/guides/vision).
    """

    type: Literal['input_image']
    """
    The type of the input item. Always `input_image`.
    """
    image_url: str | None
    detail: ImageDetail


class InputFileContent(OpenResponsesModel):
    """
    A file input to the model.
    """

    type: Literal['input_file']
    """
    The type of the input item. Always `input_file`.
    """
    filename: str | None = None
    """
    The name of the file to be sent to the model.
    """
    file_url: str | None = None
    """
    The URL of the file to be sent to the model.
    """


class MessageStatus(RootModel[Literal['in_progress', 'completed', 'incomplete']]):
    root: Literal['in_progress', 'completed', 'incomplete']


class FunctionCallStatus(RootModel[Literal['in_progress', 'completed', 'incomplete']]):
    root: Literal['in_progress', 'completed', 'incomplete']


class FunctionCall(OpenResponsesModel):
    """
    A function tool call that was generated by the model.
    """

    type: Literal['function_call']
    """
    The type of the item. Always `function_call`.
    """
    id: str
    """
    The unique ID of the function call item.
    """
    call_id: str
    """
    The unique ID of the function tool call that was generated.
    """
    name: str
    """
    The name of the function that was called.
    """
    arguments: str
    """
    The arguments JSON string that was generated.
    """
    status: FunctionCallStatus


class FunctionCallOutputStatusEnum(
    RootModel[Literal['in_progress', 'completed', 'incomplete']]
):
    root: Literal['in_progress', 'completed', 'incomplete']
    """
    Similar to `FunctionCallStatus`. All three options are allowed here for compatibility, but because in practice these items will be provided by developers, only `completed` should be used.
    """


class Output2(RootModel[InputTextContent | InputImageContent | InputFileContent]):
    root: Annotated[
        InputTextContent | InputImageContent | InputFileContent,
        Field(discriminator='type'),
    ]
    """
    A content part that makes up an input or output item.
    """


class FunctionCallOutput(OpenResponsesModel):
    """
    A function tool call output that was returned by the tool.
    """

    type: Literal['function_call_output']
    """
    The type of the function tool call output. Always `function_call_output`.
    """
    id: str
    """
    The unique ID of the function tool call output. Populated when this item is returned via API.
    """
    call_id: str
    """
    The unique ID of the function tool call generated by the model.
    """
    output: str | list[Output2]
    status: FunctionCallOutputStatusEnum


class Content9(
    RootModel[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent
    ]
):
    root: Annotated[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent,
        Field(discriminator='type'),
    ]
    """
    A content part that makes up an input or output item.
    """


class Summary(
    RootModel[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent
    ]
):
    root: Annotated[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent,
        Field(discriminator='type'),
    ]
    """
    A content part that makes up an input or output item.
    """


class ReasoningBody(OpenResponsesModel):
    """
    A reasoning item that was generated by the model.
    """

    type: Literal['reasoning']
    """
    The type of the item. Always `reasoning`.
    """
    id: str
    """
    The unique ID of the reasoning item.
    """
    content: list[Content9] | None = None
    """
    The reasoning content that was generated.
    """
    summary: list[Summary]
    """
    The reasoning summary content that was generated.
    """
    encrypted_content: str | None = None
    """
    The encrypted reasoning content that was generated.
    """


class CompactionBody(OpenResponsesModel):
    """
    A compaction item generated by the [`v1/responses/compact` API](/docs/api-reference/responses/compact).
    """

    type: Literal['compaction']
    """
    The type of the item. Always `compaction`.
    """
    id: str
    """
    The unique ID of the compaction item.
    """
    encrypted_content: str
    """
    The encrypted content that was produced by compaction.
    """
    created_by: str | None = None
    """
    The identifier of the actor that created the item.
    """


class Error1(OpenResponsesModel):
    """
    An error that occurred while generating the response.
    """

    code: str
    """
    A machine-readable error code that was returned.
    """
    message: str
    """
    A human-readable description of the error that was returned.
    """


class FunctionTool(OpenResponsesModel):
    """
    Defines a function in your own code the model can choose to call. Learn more about [function calling](https://platform.openai.com/docs/guides/function-calling).
    """

    type: Literal['function']
    """
    The type of the function tool. Always `function`.
    """
    name: str
    """
    The name of the function to call.
    """
    description: str | None
    parameters: dict[str, Any] | None
    strict: bool | None


class Tool(RootModel[FunctionTool]):
    root: Annotated[FunctionTool, Field(discriminator='type')]
    """
    A tool that can be used to generate a response.
    """


class FunctionToolChoice(OpenResponsesModel):
    type: Literal['function']
    name: str | None = None


class AllowedToolChoice(OpenResponsesModel):
    type: Literal['allowed_tools']
    tools: list[FunctionToolChoice]
    mode: ToolChoiceValueEnum


class TextResponseFormat(OpenResponsesModel):
    type: Literal['text']


class JsonObjectResponseFormat(OpenResponsesModel):
    type: Literal['json_object']


class JsonSchemaResponseFormat(OpenResponsesModel):
    type: Literal['json_schema']
    name: str
    description: str | None
    schema_: Annotated[None, Field(alias='schema')]
    strict: bool


class TextField(OpenResponsesModel):
    format: TextResponseFormat | JsonObjectResponseFormat | JsonSchemaResponseFormat
    verbosity: VerbosityEnum | None = None


class Reasoning(OpenResponsesModel):
    """
    Reasoning configuration and metadata that were used for the response.
    """

    effort: ReasoningEffortEnum | None
    summary: ReasoningSummaryEnum | None


class InputTokensDetails(OpenResponsesModel):
    """
    A breakdown of input token usage that was recorded.
    """

    cached_tokens: int
    """
    The number of input tokens that were served from cache.
    """


class OutputTokensDetails(OpenResponsesModel):
    """
    A breakdown of output token usage that was recorded.
    """

    reasoning_tokens: int
    """
    The number of output tokens that were attributed to reasoning.
    """


class Usage(OpenResponsesModel):
    """
    Token usage statistics that were recorded for the response.
    """

    input_tokens: int
    """
    The number of input tokens that were used to generate the response.
    """
    output_tokens: int
    """
    The number of output tokens that were generated by the model.
    """
    total_tokens: int
    """
    The total number of tokens that were used.
    """
    input_tokens_details: InputTokensDetails
    output_tokens_details: OutputTokensDetails


class Item1(OpenResponsesModel):
    pass


class Item3(FunctionCall, Item1):
    pass


class Item4(FunctionCallOutput, Item1):
    pass


class Item5(ReasoningBody, Item1):
    pass


class Item6(CompactionBody, Item1):
    pass


class Item71(OpenResponsesModel):
    pass


class Item73(FunctionCall, Item71):
    pass


class Item74(FunctionCallOutput, Item71):
    pass


class Item75(ReasoningBody, Item71):
    pass


class Item76(CompactionBody, Item71):
    pass


class ResponseReasoningSummaryPartAddedStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated a reasoning summary part was added.
    """

    type: Literal['response.reasoning_summary_part.added']
    """
    The type of the event, always `response.reasoning_summary_part.added`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    summary_index: int
    """
    The index of the summary part that was added.
    """
    part: Annotated[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent,
        Field(discriminator='type'),
    ]
    """
    A content part that makes up an input or output item.
    """


class ResponseReasoningSummaryPartDoneStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated a reasoning summary part was completed.
    """

    type: Literal['response.reasoning_summary_part.done']
    """
    The type of the event, always `response.reasoning_summary_part.done`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    summary_index: int
    """
    The index of the summary part that was completed.
    """
    part: Annotated[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent,
        Field(discriminator='type'),
    ]
    """
    A content part that makes up an input or output item.
    """


class ResponseContentPartAddedStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated a content part was added.
    """

    type: Literal['response.content_part.added']
    """
    The type of the event, always `response.content_part.added`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    content_index: int
    """
    The index of the content part that was added.
    """
    part: Annotated[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent,
        Field(discriminator='type'),
    ]
    """
    A content part that makes up an input or output item.
    """


class ResponseContentPartDoneStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated a content part was completed.
    """

    type: Literal['response.content_part.done']
    """
    The type of the event, always `response.content_part.done`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    content_index: int
    """
    The index of the content part that was completed.
    """
    part: Annotated[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent,
        Field(discriminator='type'),
    ]
    """
    A content part that makes up an input or output item.
    """


class ResponseOutputTextDeltaStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated output text was incrementally added.
    """

    type: Literal['response.output_text.delta']
    """
    The type of the event, always `response.output_text.delta`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    content_index: int
    """
    The index of the content part that was updated.
    """
    delta: str
    """
    The text delta that was appended.
    """
    logprobs: list[LogProb] | None = None
    """
    The token log probabilities that were emitted with the delta, if any.
    """
    obfuscation: str | None = None
    """
    An obfuscation string that was added to pad the event payload.
    """


class ResponseOutputTextDoneStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated output text was completed.
    """

    type: Literal['response.output_text.done']
    """
    The type of the event, always `response.output_text.done`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    content_index: int
    """
    The index of the content part that was completed.
    """
    text: str
    """
    The final text that was emitted.
    """
    logprobs: list[LogProb] | None = None
    """
    The token log probabilities that were emitted with the final text, if any.
    """


class ResponseRefusalDeltaStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated refusal text was incrementally added.
    """

    type: Literal['response.refusal.delta']
    """
    The type of the event, always `response.refusal.delta`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    content_index: int
    """
    The index of the refusal content that was updated.
    """
    delta: str
    """
    The refusal text delta that was appended.
    """


class ResponseRefusalDoneStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated refusal text was completed.
    """

    type: Literal['response.refusal.done']
    """
    The type of the event, always `response.refusal.done`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    content_index: int
    """
    The index of the refusal content that was completed.
    """
    refusal: str
    """
    The final refusal text that was emitted.
    """


class ResponseReasoningDeltaStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated reasoning text was incrementally added.
    """

    type: Literal['response.reasoning.delta']
    """
    The type of the event, always `response.reasoning.delta`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    content_index: int
    """
    The index of the reasoning content that was updated.
    """
    delta: str
    """
    The reasoning text delta that was appended.
    """
    obfuscation: str | None = None
    """
    An obfuscation string that was added to pad the event payload.
    """


class ResponseReasoningDoneStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated reasoning text was completed.
    """

    type: Literal['response.reasoning.done']
    """
    The type of the event, always `response.reasoning.done`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    content_index: int
    """
    The index of the reasoning content that was completed.
    """
    text: str
    """
    The final reasoning text that was emitted.
    """


class ResponseReasoningSummaryDeltaStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated a reasoning summary was incrementally added.
    """

    type: Literal['response.reasoning_summary_text.delta']
    """
    The type of the event, always `response.reasoning_summary.delta`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    summary_index: int
    """
    The index of the summary content that was updated.
    """
    delta: str
    """
    The summary text delta that was appended.
    """
    obfuscation: str | None = None
    """
    An obfuscation string that was added to pad the event payload.
    """


class ResponseReasoningSummaryDoneStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated a reasoning summary was completed.
    """

    type: Literal['response.reasoning_summary_text.done']
    """
    The type of the event, always `response.reasoning_summary.done`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    summary_index: int
    """
    The index of the summary content that was completed.
    """
    text: str
    """
    The final summary text that was emitted.
    """


class Annotation11(OpenResponsesModel):
    pass


class Annotation12(UrlCitationBody, Annotation11):
    pass


class Annotation1(RootModel[Annotation12]):
    root: Annotation12


class ResponseOutputTextAnnotationAddedStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated an output text annotation was added.
    """

    type: Literal['response.output_text.annotation.added']
    """
    The type of the event, always `response.output_text.annotation.added`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    content_index: int
    """
    The index of the output text content that was updated.
    """
    annotation_index: int
    """
    The index of the annotation that was added.
    """
    annotation: Annotation1 | None


class ResponseFunctionCallArgumentsDeltaStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated function call arguments were incrementally added.
    """

    type: Literal['response.function_call_arguments.delta']
    """
    The type of the event, always `response.function_call_arguments.delta`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the tool call item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    delta: str
    """
    The arguments delta that was appended.
    """
    obfuscation: str | None = None
    """
    An obfuscation string that was added to pad the event payload.
    """


class ResponseFunctionCallArgumentsDoneStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated function call arguments were completed.
    """

    type: Literal['response.function_call_arguments.done']
    """
    The type of the event, always `response.function_call_arguments.done`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    item_id: str
    """
    The ID of the tool call item that was updated.
    """
    output_index: int
    """
    The index of the output item that was updated.
    """
    arguments: str
    """
    The final arguments string that was emitted.
    """


class ErrorPayload(OpenResponsesModel):
    """
    An error payload that was emitted for a streaming error event.
    """

    type: str
    """
    The error type that was emitted.
    """
    code: str | None
    message: str
    """
    The human-readable error message that was emitted.
    """
    param: str | None
    headers: dict[str, str] | None = None
    """
    The response headers that were emitted with the error, if any.
    """


class ErrorStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated an error was emitted.
    """

    type: Literal['error']
    """
    The type of the event, always `error`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    error: ErrorPayload


class Input1(RootModel[str]):
    root: Annotated[str, Field(max_length=10485760)]
    """
    A text input to the model, equivalent to a text input with the `user` role.
    """


class InputVideoContent(OpenResponsesModel):
    """
    A content block representing a video input to the model.
    """

    type: Literal['input_video']
    """
    The type of the input content. Always `input_video`.
    """
    video_url: str
    """
    A base64 or remote url that resolves to a video file.
    """


class JsonSchemaResponseFormatParam(OpenResponsesModel):
    type: Literal['json_schema'] | None = None
    """
    The type of response format being defined. Always `json_schema`.
    """
    description: str | None = None
    """
    A description of what the response format is for, used by the model to
    determine how to respond in the format.

    """
    name: str | None = None
    """
    The name of the response format. Must be a-z, A-Z, 0-9, or contain
    underscores and dashes, with a maximum length of 64.

    """
    schema_: Annotated[
        dict[str, Any] | None, Field(alias='schema', title='JSON schema')
    ] = None
    """
    The schema for the response format, described as a JSON Schema object.

    """
    strict: bool | None = None


class TextFormatParam(RootModel[TextResponseFormat | JsonSchemaResponseFormatParam]):
    root: TextResponseFormat | JsonSchemaResponseFormatParam


class InputImageContentParamAutoParam(OpenResponsesModel):
    """
    An image input to the model. Learn about [image inputs](/docs/guides/vision)
    """

    type: Literal['input_image']
    """
    The type of the input item. Always `input_image`.
    """
    image_url: ImageUrl | None = None
    detail: ImageDetail | None = None


class Content(
    RootModel[
        InputTextContentParam | InputImageContentParamAutoParam | InputFileContentParam
    ]
):
    root: Annotated[
        InputTextContentParam | InputImageContentParamAutoParam | InputFileContentParam,
        Field(discriminator='type'),
    ]
    """
    A piece of message content, such as text, an image, or a file.
    """


class UserMessageItemParam(OpenResponsesModel):
    id: str | None = None
    type: Literal['message']
    """
    The item type. Always `message`.
    """
    role: Literal['user']
    """
    The message role. Always `user`.
    """
    content: list[Content] | Content1
    """
    The message content, as an array of content parts.
    """
    status: str | None = None


class FunctionCallItemParam(OpenResponsesModel):
    id: str | None = None
    call_id: Annotated[str, Field(max_length=64, min_length=1)]
    """
    The unique ID of the function tool call generated by the model.
    """
    type: Literal['function_call']
    """
    The item type. Always `function_call`.
    """
    name: Annotated[str, Field(max_length=64, min_length=1, pattern='^[a-zA-Z0-9_-]+$')]
    """
    The name of the function to call.
    """
    arguments: str
    """
    The function arguments as a JSON string.
    """
    status: FunctionCallStatus | None = None


class Output1(
    RootModel[
        InputTextContentParam
        | InputImageContentParamAutoParam
        | InputFileContentParam
        | InputVideoContent
    ]
):
    root: Annotated[
        InputTextContentParam
        | InputImageContentParamAutoParam
        | InputFileContentParam
        | InputVideoContent,
        Field(discriminator='type'),
    ]
    """
    A piece of message content, such as text, an image, or a file.
    """


class FunctionCallOutputItemParam(OpenResponsesModel):
    """
    The output of a function tool call.
    """

    id: str | None = None
    call_id: Annotated[str, Field(max_length=64, min_length=1)]
    """
    The unique ID of the function tool call generated by the model.
    """
    type: Literal['function_call_output']
    """
    The type of the function tool call output. Always `function_call_output`.
    """
    output: Output | list[Output1]
    """
    Text, image, or file output of the function tool call.
    """
    status: FunctionCallStatus | None = None


class ItemParam(
    RootModel[
        ItemReferenceParam
        | ReasoningItemParam
        | CompactionSummaryItemParam
        | UserMessageItemParam
        | SystemMessageItemParam
        | DeveloperMessageItemParam
        | AssistantMessageItemParam
        | FunctionCallItemParam
        | FunctionCallOutputItemParam
    ]
):
    root: (
        ItemReferenceParam
        | ReasoningItemParam
        | CompactionSummaryItemParam
        | UserMessageItemParam
        | SystemMessageItemParam
        | DeveloperMessageItemParam
        | AssistantMessageItemParam
        | FunctionCallItemParam
        | FunctionCallOutputItemParam
    )


class TextParam(OpenResponsesModel):
    format: TextFormatParam | None = None
    """
    The format configuration for text output.
    """
    verbosity: VerbosityEnum | None = None


class CreateResponseBody(OpenResponsesModel):
    model: str | None = None
    input: Input | list[ItemParam] | None = None
    previous_response_id: str | None = None
    include: list[IncludeEnum] | None = None
    tools: list[ResponsesToolParam] | None = None
    tool_choice: ToolChoice | None = None
    metadata: MetadataParam | None = None
    text: TextParam | None = None
    temperature: float | None = None
    top_p: float | None = None
    presence_penalty: float | None = None
    frequency_penalty: float | None = None
    parallel_tool_calls: bool | None = None
    stream: bool | None = None
    """
    Whether to stream response events as server-sent events.
    """
    stream_options: StreamOptionsParam | None = None
    background: bool | None = None
    """
    Whether to run the request in the background and return immediately.
    """
    max_output_tokens: MaxOutputTokens | None = None
    max_tool_calls: MaxToolCalls | None = None
    reasoning: ReasoningParam | None = None
    safety_identifier: SafetyIdentifier | None = None
    prompt_cache_key: PromptCacheKey | None = None
    truncation: TruncationEnum | None = None
    instructions: str | None = None
    store: bool | None = None
    """
    Whether to store the response so it can be retrieved later.
    """
    service_tier: ServiceTierEnum | None = None
    top_logprobs: TopLogprobs | None = None


class WebSocketResponseCreateEvent(CreateResponseBody):
    """
    A client-sent WebSocket event that starts a Responses turn. It uses the normal response-create body plus a required `type` field.
    """

    type: Literal['response.create']
    """
    The client event type. Always `response.create`.
    """
    stream: Annotated[str | None, Field(max_length=0, min_length=1)] = None
    """
    This HTTP streaming field MUST NOT be sent in WebSocket `response.create` messages.
    """
    stream_options: StreamOptions | StreamOptions1 | None = None
    """
    This HTTP streaming options field MUST NOT be sent in WebSocket `response.create` messages.
    """
    background: Annotated[str | None, Field(max_length=0, min_length=1)] = None
    """
    This HTTP background-mode field MUST NOT be sent in WebSocket `response.create` messages.
    """


class Content8(
    RootModel[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent
        | InputVideoContent
    ]
):
    root: Annotated[
        InputTextContent
        | OutputTextContent
        | TextContent
        | SummaryTextContent
        | ReasoningTextContent
        | RefusalContent
        | InputImageContent
        | InputFileContent
        | InputVideoContent,
        Field(discriminator='type'),
    ]
    """
    A content part that makes up an input or output item.
    """


class Message(OpenResponsesModel):
    """
    A message to or from the model.
    """

    type: Literal['message']
    """
    The type of the message. Always set to `message`.
    """
    id: str
    """
    The unique ID of the message.
    """
    status: MessageStatus
    role: MessageRole
    content: list[Content8]
    """
    The content of the message
    """
    phase: Literal['commentary', 'final_answer'] | None = None
    """
    Labels an `assistant` message as intermediate commentary (`commentary`) or the final answer (`final_answer`). For models like `gpt-5.3-codex` and beyond, when sending follow-up requests, preserve and resend phase on all assistant messages. Omitting it can degrade performance. Not used for user messages.
    """


class ItemField(
    RootModel[
        Message | FunctionCall | FunctionCallOutput | ReasoningBody | CompactionBody
    ]
):
    root: Annotated[
        Message | FunctionCall | FunctionCallOutput | ReasoningBody | CompactionBody,
        Field(discriminator='type'),
    ]
    """
    An item representing a message, tool call, tool output, reasoning, or other response element.
    """


class ResponseResource(OpenResponsesModel):
    """
    The complete response object that was returned by the Responses API.
    """

    id: str
    """
    The unique ID of the response that was created.
    """
    object: Literal['response']
    """
    The object type, which was always `response`.
    """
    created_at: int
    """
    The Unix timestamp (in seconds) for when the response was created.
    """
    completed_at: int | None
    status: str
    """
    The status that was set for the response.
    """
    incomplete_details: IncompleteDetails | None
    model: str
    """
    The model that generated this response.
    """
    previous_response_id: str | None
    instructions: str | None
    output: list[ItemField]
    """
    The output items that were generated by the model.
    """
    error: Error1 | None
    tools: list[Tool]
    """
    The tools that were available to the model during response generation.
    """
    tool_choice: FunctionToolChoice | ToolChoiceValueEnum | AllowedToolChoice
    truncation: TruncationEnum
    parallel_tool_calls: bool
    """
    Whether the model was allowed to call multiple tools in parallel.
    """
    text: TextField
    top_p: float
    """
    The nucleus sampling parameter that was used for this response.
    """
    presence_penalty: float
    """
    The presence penalty that was used to penalize new tokens based on whether they appear in the text so far.
    """
    frequency_penalty: float
    """
    The frequency penalty that was used to penalize new tokens based on their frequency in the text so far.
    """
    top_logprobs: int
    """
    The number of most likely tokens that were returned at each position, along with their log probabilities.
    """
    temperature: float
    """
    The sampling temperature that was used for this response.
    """
    reasoning: Reasoning | None
    usage: Usage | None
    max_output_tokens: int | None
    max_tool_calls: int | None
    store: bool
    """
    Whether this response was stored so it can be retrieved later.
    """
    background: bool
    """
    Whether this request was run in the background.
    """
    service_tier: str
    """
    The service tier that was used for this response.
    """
    metadata: Any
    """
    Developer-defined metadata that was associated with the response.
    """
    safety_identifier: str | None
    prompt_cache_key: str | None


class ResponseCreatedStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated the response was created.
    """

    type: Literal['response.created']
    """
    The type of the event, always `response.created`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    response: ResponseResource


class ResponseQueuedStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated the response was queued.
    """

    type: Literal['response.queued']
    """
    The type of the event, always `response.queued`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    response: ResponseResource


class ResponseInProgressStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated the response was in progress.
    """

    type: Literal['response.in_progress']
    """
    The type of the event, always `response.in_progress`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    response: ResponseResource


class ResponseCompletedStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated the response was completed.
    """

    type: Literal['response.completed']
    """
    The type of the event, always `response.completed`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    response: ResponseResource


class ResponseFailedStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated the response had failed.
    """

    type: Literal['response.failed']
    """
    The type of the event, always `response.failed`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    response: ResponseResource


class ResponseIncompleteStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated the response was incomplete.
    """

    type: Literal['response.incomplete']
    """
    The type of the event, always `response.incomplete`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    response: ResponseResource


class Item2(Message, Item1):
    pass


class Item(RootModel[Item2 | Item3 | Item4 | Item5 | Item6]):
    root: Item2 | Item3 | Item4 | Item5 | Item6


class ResponseOutputItemAddedStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated an output item was added to the response.
    """

    type: Literal['response.output_item.added']
    """
    The type of the event, always `response.output_item.added`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    output_index: int
    """
    The index of the output item that was added.
    """
    item: Item | None


class Item72(Message, Item71):
    pass


class Item7(RootModel[Item72 | Item73 | Item74 | Item75 | Item76]):
    root: Item72 | Item73 | Item74 | Item75 | Item76


class ResponseOutputItemDoneStreamingEvent(OpenResponsesModel):
    """
    A streaming event that indicated an output item was completed.
    """

    type: Literal['response.output_item.done']
    """
    The type of the event, always `response.output_item.done`.
    """
    sequence_number: int
    """
    The sequence number of the event that was emitted.
    """
    output_index: int
    """
    The index of the output item that was completed.
    """
    item: Item7 | None


class CompactResponseMethodPublicBody(OpenResponsesModel):
    model: str
    """
    Model ID used to generate the response, like `gpt-5` or `o3`. OpenAI offers a wide range of models with different capabilities, performance characteristics, and price points. Refer to the [model guide](/docs/models) to browse and compare available models.
    """
    input: Input1 | list[ItemParam] | None = None
    previous_response_id: str | None = None
    instructions: str | None = None
    prompt_cache_key: PromptCacheKey | None = None


class CompactResource(OpenResponsesModel):
    id: str
    """
    The unique identifier for the compacted response.
    """
    object: Literal['response.compaction']
    """
    The object type. Always `response.compaction`.
    """
    output: list[ItemField]
    """
    The compacted list of output items.
    """
    created_at: int
    """
    Unix timestamp (in seconds) when the compacted conversation was created.
    """
    usage: Usage
